### ISSUE TITLE
XE4 - E2506 Method of parameterized type declared in interface section must not use local symbol 'TThreadHelper'

### ISSUE THREAD

**Issue by edwinyzh** [dalijap/nx-horizon#3]
Thanks for developing this event bus library, it looks very useful while being lightweight.

I'm trying to compile the tests with XE4, and got the following error, any idea as to how to solve it? Thanks.
`[dcc32 Error] NX.Horizon.pas(484): E2506 Method of parameterized type declared in interface section must not use local symbol 'TThreadHelper'
`

![2022-07-20_15h56_54](https://user-images.githubusercontent.com/541197/179929026-879f8b9c-446d-4004-abd1-00c05f93da48.png)

**Comment by dalijap** [comment]
Fixed. TThreadHelper must be declared in interface section.

**Comment by edwinyzh** [comment]
Thanks! Compiled and passed all tests.
