### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by rshuck** [dalijap/nx-horizon#4]
Sorry, not an issue but don't know where to post comments.
I wanted to say a big thank you. You saved my bacon.

I was using 'Delphi Event Bus' and was coming up against the issue you solve by using subscription.waitfor.

I've now switched to yours, it's a little wordier but more reliable.

**Comment by dalijap** [comment]
Thanks!

I am glad that you were able to solve your problem :)

Also, in this case, being more "wordier" in code, gives better performance at runtime.
